dist: focal
os: linux
language: node_js, ruby

rvm:
  - 3.2.3

cache:
  yarn: true

node_js:
  - 18

branches:
  only:
    - main

env:
  global:
    - NODE_ENV=test
    - DEBIAN_FRONTEND=noninteractive
    - CI_NODE_TOTAL=2
    - DOMAIN=localhost
    - MYAPPLE_BASE_URI=http://localhost:8080
    - MYAPPLE_API_URI=http://localhost:3000

install:
  - nvm install 18.15.0
  - node -v
  - |-
  - cd myapple-frontend
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: myapple-frontend/build
  on:
    branch: main
