language: node_js

node_js:
  - 16

cache: npm

install:
  - cd myapple-frontend
  - npm install

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main

notifications:
  email:
    if: type = cron
    recipients:
      - abdulhathi@gmail.com
    on_success: always