os: linux
language: node_js

cache:
  yarn: true

node_js:
  - 18

branches:
  only:
    - main

install:
    - nvm install 18.15.0
    - node -v
    - cd myapple-frontend
    - yarn workspaces focus --all

script:
  - npm test
  - npm run build