source "https://rubygems.org"

ruby "3.2.3"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3", ">= 7.1.3.2"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem 'rack-cors'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  # Brakeman is a free vulnerability scanner specifically designed for Ruby on Rails applications
  gem 'brakeman'
  # Cypress on Rails gem, which provides some good integrations between Cypress and Ruby on Rails.
  gem 'cypress-on-rails', '~> 1.0'
  gem "debug", platforms: %i[ mri windows ]
  gem 'factory_bot', '~> 6.2'
  gem 'kender'
  gem 'simplecov'

  # Debugging
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rails-controller-testing'
  gem 'rspec-rails', require: false
  gem 'rubocop-git'
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'brakeman'
  gem 'bundler-audit'
  gem 'faker'
  gem 'rubocop-performance', require: false
  gem 'selenium-webdriver'
  gem 'simplecov'

  gem 'factory_bot_rails'
  gem 'rspec-its', '~> 1.3'
  gem 'shoulda-matchers'
  gem 'timecop'
  gem 'webdrivers'
  gem 'webmock'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen'
  gem 'solargraph'

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen'
end

