name: Validate project

on:
  push:
    branches-ignore:
      - main
  
  jobs:
    ci_validation:
      runs-on: [self-hosted, ubuntu-latest]

      services:
        postgres:
          image: postgres:alpine
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: ${{secrets.POSTGRES_DB}}
            POSTGRES_USER: ${{secrets.POSTGRES_USER}}
            POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: API Setup
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.2.3
            working-directory: api
            bundler-cache: true
            cache-version: 1
        
        - name: Prepare Database
          working-directory: myapple-backend1
          run: ./bin/heroku_deploy.sh
        
        - name: API Tests
          working-directory: myapple-backend1
          run: bundle exec rspec spec

        - name: API Lint
          working-directory: myapple-backend1
          run: bundle exec rubocop