# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: 'Ruby on Rails CI'
on:
  push:
    branches: ['develop', 'main', '/^release.+$/', "/^travis\\//"]
  pull_request:
    branches: ['develop', 'main', '/^release.+$/', "/^travis\\//"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: No SSH
        run: |
          git config --global url."https://github".insteadOf ssh://git@github
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Checkout code
        uses: actions/checkout@v4

      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          ruby-version: 3.2.3
          working-directory: myapple-backend
          bundler-cache: true

      - name: API Tests
        working-directory: myapple-backend
        run: bundle exec rspec spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: No SSH
        run: |
          git config --global url."https://github".insteadOf ssh://git@github
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          ruby-version: 3.2.3
          working-directory: myapple-backend
          bundler-cache: true
      # Add or replace any other lints here

      - name: Brakeman
        working-directory: myapple-backend
        run: bundle exec brakeman --quiet --exit-on-warn

      - name: Security audit dependencies
        working-directory: myapple-backend
        run: bundle exec bundle-audit check --update

      # - name: Rubocop
      #   working-directory: myapple-backend
      #   run: bundle exec rubocop

      - name: rake_ci
        working-directory: myapple-backend
        run: bundle exec rake ci

  npmTest:
    runs-on: ubuntu-latest
    steps:
      - name: No SSH
        run: |
          git config --global url."https://github".insteadOf ssh://git@github
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Yarn install
        working-directory: myapple-frontend
        run: yarn install

      - name: Yarn test
        working-directory: myapple-frontend
        run: yarn test:unit

      - name: Yarn lint
        working-directory: myapple-frontend
        run: yarn lint
